INFO 2025-05-08 10:43:05,972 autoreload 21652 6956 Watching for file changes with StatReloader
INFO 2025-05-08 10:43:36,556 autoreload 21652 6956 C:\Users\cdmor\ProyectosDjango\OnePlayer\oneplayer\oneplayer\settings.py changed, reloading.
INFO 2025-05-08 10:43:38,723 autoreload 23124 17112 Watching for file changes with StatReloader
INFO 2025-05-08 10:44:03,121 autoreload 23124 17112 C:\Users\cdmor\ProyectosDjango\OnePlayer\oneplayer\oneplayer\settings.py changed, reloading.
INFO 2025-05-08 10:44:05,650 autoreload 20548 19760 Watching for file changes with StatReloader
ERROR 2025-05-08 10:44:44,655 log 20548 19156 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2025-05-08 10:44:44,688 basehttp 20548 19156 "GET / HTTP/1.1" 500 145
INFO 2025-05-08 10:50:05,368 autoreload 9012 5164 Watching for file changes with StatReloader
ERROR 2025-05-08 10:50:10,801 log 9012 18104 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2025-05-08 10:50:10,827 basehttp 9012 18104 "GET / HTTP/1.1" 500 145
ERROR 2025-05-08 10:50:11,059 log 9012 18104 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\core\signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2025-05-08 10:50:11,075 basehttp 9012 18104 "GET /favicon.ico HTTP/1.1" 500 145
INFO 2025-05-08 10:59:39,994 autoreload 16940 20844 Watching for file changes with StatReloader
ERROR 2025-05-08 11:00:16,176 log 16940 19256 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\oneplayer\oneplayerapp\views.py", line 502, in vandal_noticias_view
    return render(request, 'ONEPLAYER.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\defaulttags.py", line 320, in render
    match = condition.eval(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\models\query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\cdmor\ProyectosDjango\OnePlayer\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

ERROR 2025-05-08 11:00:17,288 basehttp 16940 19256 "GET / HTTP/1.1" 500 145
INFO 2025-05-08 11:03:40,724 autoreload 21036 6000 Watching for file changes with StatReloader
INFO 2025-05-08 11:03:48,234 basehttp 21036 12896 "GET / HTTP/1.1" 200 11440
WARNING 2025-05-08 11:03:48,331 log 21036 12896 Not Found: /static/css/style.css
WARNING 2025-05-08 11:03:48,331 basehttp 21036 12896 "GET /static/css/style.css HTTP/1.1" 404 179
WARNING 2025-05-08 11:03:48,359 log 21036 12896 Not Found: /static/img/bg-header.jpg
WARNING 2025-05-08 11:03:48,365 basehttp 21036 12896 "GET /static/img/bg-header.jpg HTTP/1.1" 404 179
WARNING 2025-05-08 11:03:48,862 log 21036 10372 Not Found: /static/img/JCARRERA.jpeg
WARNING 2025-05-08 11:03:48,870 log 21036 12896 Not Found: /static/js/navbar.js
WARNING 2025-05-08 11:03:48,870 log 21036 17496 Not Found: /static/img/MA.jpg
WARNING 2025-05-08 11:03:48,870 log 21036 16408 Not Found: /static/img/TERROR.jpg
WARNING 2025-05-08 11:03:48,878 basehttp 21036 10372 "GET /static/img/JCARRERA.jpeg HTTP/1.1" 404 179
WARNING 2025-05-08 11:03:48,878 basehttp 21036 12896 "GET /static/js/navbar.js HTTP/1.1" 404 179
WARNING 2025-05-08 11:03:48,878 basehttp 21036 17496 "GET /static/img/MA.jpg HTTP/1.1" 404 179
WARNING 2025-05-08 11:03:48,878 basehttp 21036 16408 "GET /static/img/TERROR.jpg HTTP/1.1" 404 179
INFO 2025-05-08 11:06:33,134 autoreload 21036 6000 C:\Users\cdmor\ProyectosDjango\OnePlayer\oneplayer\oneplayer\settings.py changed, reloading.
INFO 2025-05-08 11:06:35,683 autoreload 4348 18320 Watching for file changes with StatReloader
INFO 2025-05-08 11:06:44,242 basehttp 4348 22120 "GET / HTTP/1.1" 200 11440
WARNING 2025-05-08 11:06:44,355 log 4348 22120 Not Found: /static/css/style.css
WARNING 2025-05-08 11:06:44,363 basehttp 4348 22120 "GET /static/css/style.css HTTP/1.1" 404 179
WARNING 2025-05-08 11:06:44,394 log 4348 1596 Not Found: /static/img/bg-header.jpg
WARNING 2025-05-08 11:06:44,394 basehttp 4348 1596 "GET /static/img/bg-header.jpg HTTP/1.1" 404 179
WARNING 2025-05-08 11:06:44,457 log 4348 1596 Not Found: /static/js/navbar.js
WARNING 2025-05-08 11:06:44,466 basehttp 4348 1596 "GET /static/js/navbar.js HTTP/1.1" 404 179
WARNING 2025-05-08 11:06:44,491 log 4348 1596 Not Found: /static/img/TERROR.jpg
WARNING 2025-05-08 11:06:44,500 basehttp 4348 1596 "GET /static/img/TERROR.jpg HTTP/1.1" 404 179
WARNING 2025-05-08 11:06:44,507 log 4348 1596 Not Found: /static/img/JCARRERA.jpeg
WARNING 2025-05-08 11:06:44,514 basehttp 4348 1596 "GET /static/img/JCARRERA.jpeg HTTP/1.1" 404 179
WARNING 2025-05-08 11:06:44,530 log 4348 1596 Not Found: /static/img/MA.jpg
WARNING 2025-05-08 11:06:44,530 basehttp 4348 1596 "GET /static/img/MA.jpg HTTP/1.1" 404 179
